browser=chrome
//url=https://demo.guru99.com/test/simple_context_menu.html
//url=https://the-internet.herokuapp.com/drag_and_drop
//url=https://the-internet.herokuapp.com/iframe
//url=https://the-internet.herokuapp.com/windows
url=https://the-internet.herokuapp.com/dropdown